version: "3"
services:
    proxy:
        build: ./nginx
        ports:
            - 5000:3000
            - 5050:8080
        depends_on:
            - voting-app-client
            - voting-app-server
            - redis
        networks:
            - front-end
            - back-end
        profiles:
            - test
            - main
    voting-app-client:
        build: ./voting-app/client/
        ports:
            - 3000:3000
        depends_on:
            - redis
            - voting-app-server
        networks:
            - front-end
        profiles:
            - test
            - main
    voting-app-server:
        build: ./voting-app/server/
        ports:
            - 8080:8080
        depends_on:
            - redis
        networks:
            - back-end
        profiles:
            - test
            - main
    results-app-server:
        build: ./results-app/server/
        ports:
            - 8081:8081
            - 8085:8085
        depends_on:
            - mongodb
            - worker
        networks:
            - back-end
        environment:
            - MONGODB_CONNSTRING=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb
        profiles:
            - debug
            - main
    worker:
        build: ./worker
        depends_on:
            - mongodb
            - redis
        networks:
            - back-end
        environment:
            - MONGODB_CONNSTRING=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb
        profiles:
            - test
            - main
    redis:
        build: ./redis
        ports:
            - 6379:6379
        networks:
            - back-end
        profiles:
            - test
            - main
    mongodb:
        image: mongo:5.0.9
        networks:
            - back-end
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        profiles:
            - test
            - main
networks:
    front-end:
    back-end:
